### ISSUE TITLE
'convertToPinyinStringWithoutException' isn't defined for the class 'PinyinHelper'

### ISSUE THREAD

**Issue by sabriismail4** [Yidadaa/p2p-message#1]
The warning I am getting is this:
The method 'convertToPinyinStringWithoutException' isn't defined for the class 'PinyinHelper'.
Try correcting the name to the name of an existing method, or defining a method named 'convertToPinyinStringWithoutException'.dart(undefined_method)
Unfortunately it causes the app not to be compiled.
Can you tell us here how the issue can be solved ?

**Comment by Yidadaa** [comment]
Hello, thanks for your attention to my project, this is a semi-finished app, even can not send messages to another client, and I have no plan to finish it in the future, so just forget it and find another alternative project.

**Comment by sabriismail4** [comment]
I didn't know that it could not send message, but I meant it didn't start at all. Can you help with telling me, how do you write plugins for flutter ?

**Comment by Yidadaa** [comment]
I haven't wrriten any flutter plugins, so you may refer to flutter's official document for help. 

BTW, if you still want to get start with this project, install [this dart package](https://pub.dev/packages/lpinyin) and rebuild, but the UI of this app is in chinese, so it may be a little diffcult for you to understand the text in the UI hhhh

**Comment by sabriismail4** [comment]
Well, I can't start it this way too, it first wants me to fix the error. Well I thought that a plugin and a package in flutter are the same things, but it appears not to be the same then. Can you tell me a source i.e. a book link or whatever which helped you through writing this package ? Because I saw that you have experience with writing packages. Thanks in advance!

**Comment by Yidadaa** [comment]
uh.. I can't understand what you are talking about... This repo is not a package or plugin, it's a flutter application, and I have no experience with writing flutter packages or plugins, if you want to know how to write a package & plugin in flutter(or Dart?), [this link](https://flutter.dev/docs/development/packages-and-plugins/developing-packages) may help you.
